### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by antonioortegajr** [csjoblom/hackforacause-website#101]
During build there are many warnings. Some can be resolved using npm. Any left that that can not auto resolve should, like those with breaking changes can be addressed in a separate issue.

**Comment by csjoblom** [comment]
Should be fixed as part of #102 CircleCI is clear.

**Comment by csjoblom** [comment]
Nuxt should be running lintfix on save, the editor config files ryan put in should help us out with code editors. CircleCI just runs a quick build and doesn't push said build live or back to the repo here so having it fix errors and push back would be a bit of work.

**Comment by csjoblom** [comment]
Merged #102
