### ISSUE TITLE
Upgrade to Node.js 10.x or 12.x

### ISSUE THREAD

**Issue by ryanrolds** [csjoblom/hackforacause-website#105]
Currently, Circle CI is using Node.js 9.x (an unsupported dev version). I've tried to get the project running under Node.js 10.17.0 with updated modules, but it looks like there is a linter conflict with Prettier and Vue that will need to be resolved. It may be worth updating Nuxt first as this may resolve the issue, either way, CircleCI and developers should be using at least 10.x.

**Comment by csjoblom** [comment]
I updated the package requirement to 11 and removed prettier as part of #106 now we just need to update circleci

**Comment by csjoblom** [comment]
created PR #107 which is blocked by #106 merge

**Comment by csjoblom** [comment]
No longer blocked, added to #106 PR

**Comment by csjoblom** [comment]
Fixed in #106
