### ISSUE TITLE
Update Sponsors for 2020

### ISSUE THREAD

**Issue by websupergirl** [csjoblom/hackforacause-website#125]
Remove old sponsors and update logos on site for 2020.

**Comment by mattsayre** [comment]
Confirmed
City of Eugene
XS Media
UO
Lane County
Nulia

Verbal Confirm
Lara Mac Connell
KLCC
Eugene Tech
MVP

Need to be reached out to
LWP
CBT
United Way
Parking Services
SheerID
Sizzle Pie
IDX
Café Yumm
Togos
CTL
Farmers Union

**Comment by websupergirl** [comment]
I just talked to Cafe Yumm (new manager) for GGJ and they are still honoring the deal they gave last year. So we are okay there.

Also you're missing X-Team.

**Comment by mattsayre** [comment]
Yes, my bad... X Team, c/o Nikole Gipps is also on the confirmed sponsor list.

**Comment by websupergirl** [comment]
As per TAO/Cara/Rylee, remove all sponsors minus Nulia and U of O, add X-Team

**Comment by websupergirl** [comment]
Leaving XS Media as Stephen confirmed today.

**Comment by websupergirl** [comment]
To add: Farmer's Union Coffee logos
![Farmers Union Logo 1](https://user-images.githubusercontent.com/38568655/75855912-19628f80-5da8-11ea-8cf5-81c43411b760.png)

![Farmers Union Logo 1](https://user-images.githubusercontent.com/38568655/75855904-15367200-5da8-11ea-89cc-f7c484293d5b.jpg)
