### ISSUE TITLE
Add additional sposors

### ISSUE THREAD

**Issue by websupergirl** [csjoblom/hackforacause-website#132]
Farmer's Union for coffee
![Farmers Union Logo 1](https://user-images.githubusercontent.com/38568655/75856003-4616a700-5da8-11ea-8d2a-176c1238b696.jpg)
![Farmers Union Logo 1](https://user-images.githubusercontent.com/38568655/75856011-4a42c480-5da8-11ea-8ae4-1a3ce86416f0.png)

**Comment by websupergirl** [comment]
Page update should make this page look like cvent registration page in terms of layout for sponsors.

**Comment by antonioortegajr** [comment]
Event postponed, closing this issue.
