### ISSUE TITLE
Update schedule at path /schedule

### ISSUE THREAD

**Issue by codegold79** [csjoblom/hackforacause-website#133]
There is more information now that can be added to https://hackforacause.org/schedule. One piece is the Nulia location.

**Comment by websupergirl** [comment]
I think the event schedule should go up here, but also the schedule of surrounding events.

3/10 Reveal
3/26 WebDevs

**Comment by antonioortegajr** [comment]
Update location will be updated in issue https://github.com/csjoblom/hackforacause-website/issues/136 if there are more specific events that is fine and should be noted here.

**Comment by websupergirl** [comment]
The actual schedule with location is going up plus the schedule of surrounding events.

**Comment by websupergirl** [comment]
With links to the other events.

**Comment by antonioortegajr** [comment]
Event postponed, closing this issue.
