### ISSUE TITLE
URGENT: Modify website to reflect closure

### ISSUE THREAD

**Issue by websupergirl** [csjoblom/hackforacause-website#138]
1. Create page to outline cancellation policy.
2. Link all sign up and challenge submission links/buttons to this page.
3. Put yellow bar at top of home page (all pages?) with link to cancellation policy.
4. Change all items on schedule page to cancelled.

**Comment by websupergirl** [comment]
Scratch that, just remove schedule for now.

**Comment by websupergirl** [comment]
Remove date from front page.

**Comment by antonioortegajr** [comment]
Completed in above Pull
