### ISSUE TITLE
Add progressive jpegs for pages

### ISSUE THREAD

**Issue by csjoblom** [csjoblom/hackforacause-website#19]
We need to add progressive loading to each of the pages, background color should be #F0F0F0 @atmartins

**Comment by atmartins** [comment]
Clarified w/ @ralls, we want #FFF bg on these after all. One image is a jpg w/ #F0F0F0 bg, so I'll Photoshop that out and replace w/ #FFF.

**Comment by csjoblom** [comment]
@atmartins the commit above isn't in the repo anymore for some reason?
