### ISSUE TITLE
Add Google Analytics Tracking Code

### ISSUE THREAD

**Issue by ralls** [csjoblom/hackforacause-website#30]
We need to track traffic.

Implementation: https://nuxtjs.org/faq/google-analytics/

Don't use: [Nuxt Analytics Module](https://github.com/nuxt-community/analytics-module) Due to [issue #8](https://github.com/nuxt-community/analytics-module/issues/8) - possible timing issues which could result in inaccurate analytical data.

**Comment by csjoblom** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115926715-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115926715-1');
</script>

**Comment by ralls** [comment]
added in #31
