### ISSUE TITLE
Fix Social Links in Footer

### ISSUE THREAD

**Issue by csjoblom** [csjoblom/hackforacause-website#38]
They should point to TAO stuffs

**Comment by antonioortegajr** [comment]
These are the links on the TAO site http://www.techoregon.org/:

- https://www.facebook.com/techoregon/
- https://twitter.com/techoregon
- https://www.instagram.com/techoregon/
- https://www.linkedin.com/company/technology-association-of-oregon

**Comment by csjoblom** [comment]
this is fixed
