### ISSUE TITLE
Add EugeneTech.org to Sponsors

### ISSUE THREAD

**Issue by csjoblom** [csjoblom/hackforacause-website#41]
![eugtech](https://user-images.githubusercontent.com/3222182/37794319-6ad6bda2-2dce-11e8-82ae-a1e10b3a35b3.png)

**Comment by ralls** [comment]
Any specific order that this should have?

**Comment by csjoblom** [comment]
@ralls I'd say we just add it to the bottom for now unless Mark pipes up.

**Comment by atmartins** [comment]
Here are some others to update/add

![mozilla](https://user-images.githubusercontent.com/1334983/37866044-32c13d32-2f42-11e8-89e7-edd0bc1408e9.jpg)
![sizzlepie](https://user-images.githubusercontent.com/1334983/37866045-32d61522-2f42-11e8-9116-fe06c15d8ea3.jpg)
![united_way](https://user-images.githubusercontent.com/1334983/37866046-32e9e0e8-2f42-11e8-8d2d-250ece925d0a.jpg)
![usi](https://user-images.githubusercontent.com/1334983/37866047-32ff6b5c-2f42-11e8-986c-940a00746d85.png)
<img width="377" alt="lunarlogic" src="https://user-images.githubusercontent.com/1334983/37866187-5052116c-2f44-11e8-8e6c-2c5ae5aec352.png">
![sheerid](https://user-images.githubusercontent.com/1334983/37866190-5b5d23d0-2f44-11e8-913f-d7d944e089c5.png)
