### ISSUE TITLE
Copy Update for Home and Submission Form

### ISSUE THREAD

**Issue by hessmichael** [csjoblom/hackforacause-website#62]
**Homepage**

You need a problem solved. We need problems to solve.

Submit your idea for a Hack for a Cause challenge by February 8.

**Submission form**

You need a problem solved. We need problems to solve.

In as much detail as possible, describe a Goldilocks Problem – small enough to be progressed over a weekend, but large enough to make a real difference.

Last year, Hack for a Cause participants worked on interactive art pieces, websites and data collection services for local non-profits, and even an augmented reality game to stimulate economic development.

See all the 2018 challenges.

Submit your big idea for the 2019 teams by February 8.

Also here: https://docs.google.com/document/d/1h1jKNjhS_Roga8w9Uo96plB8Tu06CYh9Fg4laxa1gLk/edit

**Comment by ralls** [comment]
- [ ] Homepage
- [x] Submission form

**Comment by websupergirl** [comment]
The Google Form needs the surrounding content (header/etc) removed for 2020.

Past event needs photos link update.

**Comment by antonioortegajr** [comment]
This form has already been used for 2020. Any changes to copy can be addressed in a new issue.
