### ISSUE TITLE
Embed 2019 Solution Videos to website

### ISSUE THREAD

**Issue by mattsayre** [csjoblom/hackforacause-website#90]
Need to embed these new video to celebrate past teams/solutions and to give a sense of what comes out of the event for junior developers who are considering participating in 2020.

https://youtu.be/DIE3xiq3-jA
https://youtu.be/Wa8SeadUHro
https://youtu.be/s8A6xO-TpKc
https://youtu.be/6VCwBKpLlAs
https://youtu.be/ndGurVbeuRw
https://youtu.be/KXNdt407gsc
https://youtu.be/Bu46TYSMqQc
https://youtu.be/TR-jMyrks60
https://youtu.be/ESgP5ezwRpw
https://youtu.be/RICE4_8dSro
https://youtu.be/2-xp3cUGsd0
https://youtu.be/kjTfkt-djT0

**Comment by antonioortegajr** [comment]
Videos added in https://github.com/csjoblom/hackforacause-website/pull/95
