### ISSUE TITLE
Update team page for 2020

### ISSUE THREAD

**Issue by antonioortegajr** [csjoblom/hackforacause-website#98]
The team page should be updated for 2020 as there have been some changes this year.

This does require an updated list of people and photo assets for each.

**Comment by codegold79** [comment]
Frankie Gold
Technical Staff, Application Platforms
VMware

I use a lot of different images of the sun for my profile pictures. 

Here's one that's from NASA, which I cropped, and it can be freely used on websites: 
![codegold-edit](https://user-images.githubusercontent.com/17328443/66692565-7e301880-ec54-11e9-99c6-b7edf8445160.png)

Feel free to do more cropping to get the desired proportion.

**Comment by websupergirl** [comment]
Eric D. Wills
Senior Instructor
Computer Science
University of Oregon

![eric](https://user-images.githubusercontent.com/38568655/67263147-1fd91600-f45c-11e9-942d-0e9a03ba256e.jpg)

**Comment by websupergirl** [comment]
Frankie Gold
Data Engineer
IDX Broker

**Comment by websupergirl** [comment]
Remove:
Shelly Galvin
Emily Clyde
Chris Sjoblom
Lee Ralls

Missing/Unknown:
Bishop Lafer
Sylvia Barry
Diego Kourchenko
Jeff Petry
Antonio Ortega Jr
Lara?
Eric Hadley

**Comment by websupergirl** [comment]
Sarah Koski
Creative Nonprofit Partnerships Consultant

![sarahkoski_smile](https://user-images.githubusercontent.com/38568655/67263310-92e28c80-f45c-11e9-819f-087ca29cb4d6.jpg)

**Comment by websupergirl** [comment]
Jared Swezey
CTO
UpTime Sciences

![Swezeyheadshot](https://user-images.githubusercontent.com/38568655/67263386-d6d59180-f45c-11e9-951f-bea1f9bff0f9.png)

**Comment by websupergirl** [comment]
Stephen Parac
Chief Operations Officer
XS Media

![Stephen Parac](https://user-images.githubusercontent.com/38568655/67263417-f2409c80-f45c-11e9-9b88-783f34131d60.jpg)

**Comment by websupergirl** [comment]
Nikole Gipps
WordPress Engineer
X-Team

![nikolegipps_h4ac](https://user-images.githubusercontent.com/38568655/67263924-6760a180-f45e-11e9-81f2-bc4e87b87c49.jpg)

**Comment by antonioortegajr** [comment]
Deadline for picture collection is Monday Nov 17th.

**Comment by Jess-Morris** [comment]
Jess Morris
Growth Marketing & Analytics Consultant
Mammoth Growth
![image](https://user-images.githubusercontent.com/49656352/68904943-363d5f00-06f4-11ea-8bc5-3e0665a8ff9f.png)

**Comment by ashespinoza** [comment]
Ashley Espinoza
Sector Strategy Director
Lane Workforce Partnership

![Headshots -3](https://user-images.githubusercontent.com/57777414/68905191-2d995880-06f5-11ea-9476-49c3bb2e6195.jpg)

**Comment by websupergirl** [comment]
So this isn't complete but it incorporates some of the ideas I ran by Matt regarding the page. I think it lends credibility to the thing + it's easier to swap people out year by year if they aren't all in the same image block + it's super responsive for mobile/desktop/tablet. Thoughts? 

Also please feel free to comment on the text at the top which reads

> The Hack for a Cause Steering Committee brings together local leaders in the technology, non-profit and education sectors to make sure our participants, champions, volunteers, and community have a positive experience and meaningful event.

right now.

![screencapture-localhost-3000-meet-our-team-2019-11-17-23_16_49](https://user-images.githubusercontent.com/38568655/69032370-25f5e000-0991-11ea-885e-b5d4beca501f.png)

**Comment by markdav-is** [comment]
I'm assuming if we don't upload a new photo you'll use the existing ones?

**Comment by websupergirl** [comment]
I have the title and picture you sent me in the latest PR @nohorse 
![BD5-11-15-headshot](https://user-images.githubusercontent.com/38568655/69180640-7882e980-0ac2-11ea-8961-136592223352.jpg)

**Comment by antonioortegajr** [comment]
Page updated in https://github.com/csjoblom/hackforacause-website/pull/119
